version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: ${CodeBuildServiceRole}
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:2.0

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r ./requirements.txt
      # - python ./application.py <- this might block...
      - python -m pytest -s test_mainManager.py --api ${TmpUrl}
      - echo "End of tests"
