version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r ./requirements.txt
      # - python ./application.py <- this might block...
      - python -m pytest -s test_mainManager.py 