version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: ${CodeBuildServiceRole}
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:2.0

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      # Install the dependancies:
      - pip install -r ./requirements.txt
      - pytest -s test_mainManager.py --api ${TmpUrl} --dont-run-file known_failures_test_api --dont-run-file known_bugs
      # Broke apart to run threaded test seperatly, but threads break logging. Tmp dissable:
        # - python -m pytest -s -m parallel -n auto test_mainManager.py --api ${TmpUrl}
        # - python -m pytest -s -m serial test_mainManager.py --api ${TmpUrl}
      - echo "End of building this..."
