AWSTemplateFormatVersion: 2010-09-09

Description: Resources that every SearchAPI stack share

Parameters:
  RegistryName:
    Type: String
    Description: "Name of ECR that SearchAPI stacks will use. Converts to all lowercase."
    Default: "SearchAPI"

Resources:

  ## Needed to break this out from the SearchAPI stack itself, because
  #    there's no way to create an ecr, push a container, then have
  #    lambda *use* that container if they're all in the same stack.
  DockerECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        # You need the Strings macro to use this (cloudformation/cf-strings-macro.yml):
        Fn::Transform:
          Name: String
          Parameters:
            InputString: !Ref RegistryName
            Operation: Lower
      LifecyclePolicy:
        # 1) Always keep one prod image around. NOTE: You can't match it directly! A tag like "prod-asdf" will also match, since it's prefixed.
        # 2) Don't fill up on untagged images, they're outdated if untagged anyways.
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep ALL 'prod*' images around, regardless of any other rules. No way to specify JUST 'prod', so keeping everything.",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["prod"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 999999999
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Keep only some untagged images for cache, expire all others.",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      # Let lambda functions in this account, pull this container to use
      RepositoryPolicyText: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "LambdaECRImageRetrievalPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              },
              "Action": [
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer"
              ]
            }
          ]
        }

  # A WAF for all lambda-based instances to share
  CloudFrontWAF:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${AWS::StackName}-Cloudfront-WAF
      DefaultAction:
        Allow: {}
      Scope: CLOUDFRONT
      Rules:
        - Name: !Sub ${AWS::StackName}-RateLimiter
          Priority: 0
          Action:
            Block:
              CustomResponse:
                CustomResponseBodyKey: rate_limit_response_1250
                ResponseCode: 429
          Statement:
            RateBasedStatement:
              Limit: 1250
              AggregateKeyType: IP
              ScopeDownStatement:
                ByteMatchStatement:
                  SearchString: /services/search/param
                  FieldToMatch:
                    UriPath: {}
                  PositionalConstraint: STARTS_WITH
                  TextTransformations:
                    - Priority: 0
                      Type: NONE
          VisibilityConfig:
            SampledRequestsEnabled: True
            CloudWatchMetricsEnabled: True
            MetricName: ip_rate_limit
      VisibilityConfig:
        SampledRequestsEnabled: True
        CloudWatchMetricsEnabled: True
        MetricName: !Sub /aws/wafv2/${AWS::StackName}-RateLimiter
      CustomResponseBodies:
        rate_limit_response_1250:
          ContentType: APPLICATION_JSON
          Content: "{\n    \"error\": {\n        \"report\": \"Rate limited, please reduce your request rate to 250/minute or less\",\n        \"type\": \"RATE_LIMITED\"\n    }\n}"

Outputs:
  RegistryUri:
    Value: !GetAtt DockerECR.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RegistryUri"
  WafLambdaArn:
    Value: !GetAtt CloudFrontWAF.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WafLambda-Arn"
