


### A WIP idea, might impliment if other tests require custom cli arguments:
### (Might move '--api' to this at that point too)
# add_cli_options:
# - Change API:
#     usage: --api # CLI usage
#     help: "Override which api ALL .yml tests use with this. (LOCAL/DEV/TEST/PROD, or url)."
#     action: store # store/store_true, etc. Same as argparse
#     default: Null
#     key: api # What to look up in conftest.cli_args dict it returns
#     verify_method: verify_api # If you want to verify what the user passes into this meets spicific requirements


api_urls:
  local: http://127.0.0.1:5000/
  dev: https://api-dev.asf.alaska.edu/
  dev-staging: https://api-dev-staging.asf.alaska.edu
  test: https://api-test.asf.alaska.edu/
  test-staging: https://api-test-staging.asf.alaska.edu
  test-beanstalk: https://api-test-beanstalk.asf.alaska.edu/
  prod: https://api.daac.asf.alaska.edu/
  prod-staging: https://api-prod-private-staging.asf.alaska.edu/
  prod-private: https://api-prod-private.asf.alaska.edu/

  default: prod
  api_prod_list: [ prod, prod-staging, prod-private ]


test_types:
- WKT Validator Endpoint:
    required_keys: test wkt
    method: test_WKTValidatorEndpoint
    variables:
      endpoint: "/services/utils/wkt"

- Files To Wkt Endpoint:
    required_keys: file wkt
    method: test_FilesToWKTEndpoint
    variables:
      endpoint: "/services/utils/files_to_wkt"

- Mission List Endpoint:
    required_keys: misson_list_size_min
    method: test_MissionListEndpoint
    variables:
      endpoint: "/services/utils/mission_list"

- Date Parser Endpoint:
    required_keys: date
    method: test_DateParserEndpoint
    variables:
      endpoint: "/services/utils/date"

- Baseline Endpoint:
    required_keys: master
    method: test_BaselineEndpoint
    variables:
      endpoint: "/services/search/baseline"
      maturity: prod

- Get Data from API:
    method: test_URLManagerSearch
    variables:
      endpoint: "/services/search/param"
      maturity: prod
