openapi: 3.0.1
info:
  title: ASF Search API
  description: This is the Alaska Satellite Facility Search API
  termsOfService: https://www.asf.alaska.edu/SearchAPIToS
  contact:
    email: uso@asf.alaska.edu
  license:
    name: Need a license
    url: https://www.asf.alaska.edu/SearchAPILicense
  version: 1.0.0
externalDocs:
  description: Find out more about the Search API and related topics
  url: https://www.asf.alaska.edu/SearchAPIMoreInfo
servers:
- url: https://api.daac.asf.alaska.edu
- url: https://bulk-download.asf.alaska.edu

tags:
- name: 'API Info'
  description: Retrieve info about the API
- name: 'Search'
  description: Search ASF's data archive
- name: 'Bulk Download'
  description: 'Retrieve a bulk download python script'
- name: 'Utilities'
  description: 'Various utility endpoints'

paths:
  /reference:
    get:
      tags:
      - 'API Info'
      summary: Retrieve this document
      operationId: apiRef
      responses:
        200:
          description: Retrieve this document
  /health:
    get:
      tags:
      - 'API Info'
      summary: Check API and back end health
      operationId: apiHealth
      responses:
        200:
          description: JSON data containing detailed API health report

  /services/search/param:
    post:
      tags:
      - 'Search'
      summary: Execute a query and retrieve the results
      operationId: dataSearch
      responses:
        200:
          description: blah
        400:
          description: Invalid input
          content: {}
  /:
    get:
      tags:
      - 'Bulk Download'
      summary: Retrieve a python bulk download script as an attachment
      operationId: bulkGet
      responses:
        200:
          description: Python bulk download script with embedded URLs as specified; content headers set as attachment
  /view:
    get:
      tags:
      - 'Bulk Download'
      summary: Retrieve a python bulk download script
      operationId: bulkView
      responses:
        200:
          description: Python bulk download script with embedded URLs as specified; content headers set to allow viewing in browser
  /help:
    get:
      tags:
      - 'Bulk Download'
      summary: Retrieve reference docs specific to bulk download API
      operationId: bulkHelp
      responses:
        200:
          description: HTML doc containing API reference material
  /services/utils/wkt:
    get:
      tags:
      - 'Utilities'
      summary: Check API and backend health
      operationId: utilsWKT
      responses:
        200:
          description: JSON data containing detailed API health report
  /services/utils/date:
    get:
      tags:
      - 'Utilities'
      summary: Check API and backend health
      operationId: utilsDate
      responses:
        200:
          description: JSON data containing detailed API health report
  /services/utils/files_to_wkt:
    get:
      tags:
      - 'Utilities'
      summary: Check API and backend health
      operationId: utilsFilesToWKT
      responses:
        200:
          description: JSON data containing detailed API health report
  /services/utils/mission_list:
    get:
      tags:
      - 'Utilities'
      summary: Check API and backend health
      operationId: utilsMissions
      responses:
        200:
          description: JSON data containing detailed API health report
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Pet:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
      xml:
        name: Pet
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
