name: Update SearchAPI Stack

on:
  # Github Actions doesn't support Yaml Anchors! :smiling_face_with_tear:
  # If you add a branch, change it in ALL triggers
  push:
    branches-ignore:
      - prod

  pull_request:
    branches-ignore:
      - prod
    types:
      - opened
      - reopened
      - synchronize

jobs:
  deploy-SearchAPI:
    runs-on: ubuntu-latest
    environment: non-prod
    # Run if someone with write permissions did the change (the push trigger),
    # OR Run *only* if the PR came from a branch we control (so forks don't trigger)
    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/reusable-deploy-SearchAPI
        with:
          # Inputs:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.ref_name }}
          MATURITY: devel
          # Secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Pytest
        # If it's writing to a branch, the pull request to that branch already
        # passed, OR it's a developing branch that doesn't need PR's. No need
        # to run suite either way.
        if: github.event_name == 'pull_request'
        run: |
          echo "TODO"
