name: Delete SearchAPI Stack

on:
  # Branch deleted
  delete:
    branches-ignore:
      - prod

  # Pull request closed (includes merged)
  pull_request:
    types:
      - closed
    branches-ignore:
      - prod

jobs:
  delete-SearchAPI:
    runs-on: ubuntu-latest
    environment: non-prod
    # Not sure I need the same fork check here. Just in case
    if: |
      (
        github.event_name == 'delete' &&
        github.event.ref_type == 'branch'
      ) ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:

      - name: Craft SearchAPI variables
        id: variables
        env:
          REF_NAME: ${{ github.ref_name }}
        ## Special chars are replaced with '-', and:
        #   If push, tag is name of branch
        #   If pull_request, tag becomes '<pr_number>-merge' (slash is replaced by '-')
        run: |
          echo "::set-output name=tag-name::${REF_NAME//[^[:alnum:]]/-}"

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete SearchAPI Stack
        run: |
          aws cloudformation delete-stack \
              --stack-name="SearchAPI-${{ steps.variables.outputs.tag-name }}"
          aws cloudformation wait stack-delete-complete \
              --stack-name="SearchAPI-${{ steps.variables.outputs.tag-name }}"
