name: Update Main Stack

on:
  push:

jobs:
  deploy_cf:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secret.AWS_REGION }}

      - name: Update Strings Macro
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CFN-StringMacros
          template: cloudformation/single-deploy-string-macros.yml
          capabilities: CAPABILITY_IAM

      - name: Update SearchAPI ECR
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ECR-SearchAPI
          template: cloudformation/single-deploy-ecr.yml

      - name: Get ECR URI
        shell: bash
        run: |
          export AWS_URI=$(aws cloudformation describe-stacks \
            --query "Stacks[?StackName=='ECR-SearchAPI'].Outputs[0][?OutputKey=='RegistryUri'].OutputValue" \
            --output=text)
          echo "${AWS_URI}:${{github.ref_name}}"
          echo "DOCKER_IMAGE=${AWS_URI}:${{github.ref_name}}" >> $GITHUB_ENV
