name: Deleted Branch - SearchAPI Stack (non-prod)

on:
  delete:
    branches-ignore:
      - prod



jobs:
  delete-stack-non-prod-branch:
    # If a branch specifically, was deleted.
    if: github.event.ref_type == 'branch'
    uses: ./.github/workflows/reusable-DeleteStack-SearchAPI.yml
    with:
      # TAG different for both delete branch, and delete PR.
      TAG: ${{ github.event.ref }}
      environment: non-prod
    # What secrets from the environment, the workflow should have access to:
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
