name: Update Main Stack

on:
  push:

jobs:
  deploy_cf:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Strings Macro
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CFN-StringMacros
          template: cloudformation/single-deploy-string-macros.yml
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"

      - name: Update SearchAPI ECR
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ECR-SearchAPI
          template: cloudformation/single-deploy-ecr.yml
          no-fail-on-empty-changeset: "1"

      # - name: Get ECR URI
      #   shell: bash
      #   run: |
      #     export AWS_URI=$(aws cloudformation describe-stacks \
      #       --stack-name ECR-SearchAPI \
      #       --query "Stacks[?StackName=='ECR-SearchAPI'].Outputs[0][?OutputKey=='RegistryUri'].OutputValue" \
      #       --output=text)
      #     echo "${AWS_URI}:${{github.ref_name}}"
      #     echo "DOCKER_IMAGE=${AWS_URI}:${{github.ref_name}}" >> $GITHUB_ENV

      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Container
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: searchapi
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t "${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}" .
          docker push "${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
