on:
  workflow_call:
    inputs:

      TAG:
        required: true
        description: The unique ID for the stack, everything after 'SearchAPI-'.
        type: string

      AWS_REGION:
        required: False
        description: What region in AWS to run in.
        default: us-east-1
        type: string

      environment:
        required: True
        description: The GitHub Environment to use.
        type: string

    secrets:
      # AWS Auth:
      AWS_ACCESS_KEY_ID:
        description: The access key for AWS.
        required: True
      AWS_SECRET_ACCESS_KEY:
        description: The secret access key for AWS.
        required: True

jobs:
  delete-SearchAPI:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Delete SearchAPI Stack w/ Makefile
        run: |
          make -e TAG=${{ inputs.TAG }} delete-searchapi-stack
