


on:
  workflow_call:
    inputs:

      TAG_NAME:
        required: true
        description: The unique ID for the stack, everything after 'SearchAPI-'.
        type: string

      environment:
        required: True
        description: The GitHub Environment to use.
        type: string

    secrets:
      # AWS Auth:
      AWS_ACCESS_KEY_ID:
        description: The access key for AWS.
        required: True
      AWS_SECRET_ACCESS_KEY:
        description: The secret access key for AWS.
        required: True

jobs:
  delete-SearchAPI:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - name: Craft SearchAPI variables
        id: variables
        ## Special chars are replaced with '-', and:
        run: |
          echo "::set-output name=tag-name::${NAME//[^[:alnum:]]/-}"

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete SearchAPI Stack
        run: |
          aws cloudformation delete-stack \
              --stack-name="SearchAPI-${{ steps.variables.outputs.tag-name }}"
          aws cloudformation wait stack-delete-complete \
              --stack-name="SearchAPI-${{ steps.variables.outputs.tag-name }}"
