name: Update Staging Stack (PR)

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      # - edited ?

jobs:
  deploy_cf:
    runs-on: ubuntu-latest
    # Don't run ANY of this unless the PR came from one of our branches (so forks don't trigger)
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # TODO: Change to https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation
        shell: bash
        run: |
          make -e BRANCH=${{github.ref_name}}-staging all
