name: Wait for AWS hook

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize
jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting
        run: sleep 30
